 <div class="propertySearchForm">
        <select name="teamMember" id="teamMember" onchange="MM_jumpMenu('parent',this,0)">
                <option selected="selected">- Search All Projects -</option>                  
                <option value="ariel_south.php">Ariel South</option>
                <option value="bella_riverside.php">Bella Vista and Riverside</option>
                <option value="canby_village.php">Canby Village</option>
                <option value="castle_rock.php">Castle Rock</option>
                <option value="cedar_park.php">Cedar Park</option>
                <option value="clark_village.php">Clark Village</option>
                <option value="community_partners.php">Community Partners</option>
                <option value="ellington.php">Ellington </option>
                <option value="estate_hotel.php">Estate Hotel</option>
                <option value="farmington_meadows.php">Farmington Meadows</option>
                <option value="farmworker_housing.php">Farmworker Housing</option>
                <option value="fruit_valley.php">Fruit Valley</option>
                <option value="glenhaven.php">Glenhaven</option>
                <option value="golden_valley.php">Golden Valley Brewery</option>
                <option value="greenburg_oaks.php">Greenburg Oaks</option>
                <option value="greenview_terrace.php">Greenview Terrace</option>
                <option value="hewitt.php">Hewitt</option>
                <option value="indian_creek.php">Indian Creek</option>
                <option value="ironwood.php">Ironwood</option>
                <option value="jefferson_station.php">Jefferson Station</option>
                <option value="june_manor.php">June Manor</option>
                <option value="juniper_1.php">Juniper Gardens</option>
                <option value="juniperGarden_II.php">Juniper Gardens II</option>
                <option value="the_knoll.php">The Knoll at Tigard</option>
                <option value="lincoln_village.php">Lincoln Village</option>
                <option value="linnhaven.php">Linnhaven</option>
                <option value="mccoy_village.php">McCoy Village</option>
                <option value="mlk_manor.php">MLK Manor</option>
                <option value="mt_hood_community.php">Mt. Hood Community</option>
                <option value="nawikka.php">Nawikka</option>
                <option value="north_main_village.php">North Main Village</option>
                <option value="nuevo_amanecer.php">Nuevo Amanecer</option>
                <option value="nuevo_2.php">Nuevo Amanecer 4</option>
                <option value="nye_beach_hotel.php">Nye Beach Hotel</option>
                <option value="ortiz_kitchen.php">Ortiz Center Kitchen</option>
                <option value="orchards_plaza.php">Orchards Plaza</option>
                <option value="parkland_terrace.php">Parkland Terrace</option>
                <option value="parkside_village.php">Parkside Village</option>
                <option value="pisqah_harriet.php">Pisqah/Harriet</option>
                <option value="plaza_los_robles.php">Plaza Los Robles</option>
                <option value="rivermark_hawthorne.php">Rivermark Hawthorne</option>
                <option value="riverplace.php">Riverplace</option>
                <option value="salem_24hr_fitness.php">Salem 24hr Fitness</option>
                <option value="sandhill.php">Sandhill</option>
                <option value="shoreview_dental.php">Shoreview Dental</option>
                <option value="solhaven.php">Solhaven</option>
                <option value="stewart_terrace.php">Stewart Terrace</option>
                <option value="st_joesph.php">St. Joseph Shelter</option>
                <option value="stonebrook.php">Stonebrook</option>
                <option value="sunrise.php">Sunrise</option>
                <option value="summit_park.php">Summit Park</option>
                <option value="the_village.php">The Village at Monmouth</option>
                <option value="tillamook_ymca.php">Tillamook YMCA</option>
                <option value="tillicum_court.php">Tillicum</option>
                <option value="tri_harbor.php">Tri-Harbor</option>
                <option value="tryon_mews.php">Tryon Mews</option>
                <option value="uptown.php">Uptown Tower</option>
                <option value="vermont_springs.php">Vermont Springs</option>
                <option value="villebois_dental.php">Villebois Dental</option>
                <option value="villa_de_suenos.php">Villa de Suenos</option>
                <option value="villa_West.php">Villa West</option>
                <option value="vittoria.php">Vittoria</option>
                <option value="walnutPark.php">Walnut Park</option>
                <option value="watercrest.php">Watercrest</option>
                <option value="west_alameda.php">West Alameda</option>
                <option value="westgate_terrace.php">Westgate Terrace</option>

        </select></div></div>