<div id="propertySearchDrop">
         <div class="propertySearchForm">
        <select name="teamMember" id="teamMember" onchange="MM_jumpMenu('parent',this,0)">
                <option selected="selected">- Search All Projects -</option>                  
                <option value="projects/ariel_south.php">Ariel South</option>
                <option value="projects/bella_riverside.php">Bella Vista and Riverside</option>
                <option value="projects/canby_village.php">Canby Village</option>
                <option value="projects/castle_rock.php">Castle Rock</option>
                <option value="projects/cedar_park.php">Cedar Park</option>
                <option value="projects/clark_village.php">Clark Village</option>
                <option value="projects/community_partners.php">Community Partners</option>
                <option value="projects/ellington.php">Ellington </option>
                <option value="projects/estate_hotel.php">Estate Hotel</option>
                <option value="projects/farmworker_housing.php">Farmworker Housing</option>
                <option value="projects/farmington_meadows.php">Farmington Meadows</option>
                <option value="projects/fruit_valley.php">Fruit Valley</option>
                <option value="projects/glenhaven.php">Glenhaven</option>
                <option value="projects/golden_valley.php">Golden Valley Brewery</option>
                <option value="projects/greenburg_oaks.php">Greenburg Oaks</option>
                <option value="projects/greenview_terrace.php">Greenview Terrace</option>
                <option value="projects/hewitt.php">Hewitt</option>
                <option value="projects/indian_creek.php">Indian Creek</option>
                <option value="projects/ironwood.php">Ironwood</option>
                <option value="projects/jefferson_station.php">Jefferson Station</option>
                <option value="projects/june_manor.php">June Manor</option>
                <option value="projects/juniper_1.php">Juniper Gardens</option>
                <option value="projects/juniperGarden_II.php">Juniper Gardens II</option>
                <option value="projects/the_knoll.php">The Knoll at Tigard</option>
                <option value="projects/lincoln_village.php">Lincoln Village</option>
                <option value="projects/linnhaven.php">Linnhaven</option>
                <option value="projects/mccoy_village.php">McCoy Village</option>
                <option value="projects/mlk_manor.php">MLK Manor</option>
                <option value="projects/mt_hood_community.php">Mt. Hood Community</option>
                <option value="projects/nawikka.php">Nawikka</option>
                <option value="projects/north_main_village.php">North Main Village</option>
                <option value="projects/nuevo_amanecer.php">Nuevo Amanecer</option>
                <option value="projects/nuevo_2.php">Nuevo Amanecer 4</option>
                <option value="projects/nye_beach_hotel.php">Nye Beach Hotel</option>
                <option value="projects/ortiz_kitchen.php">Ortiz Center Kitchen</option>
                <option value="projects/orchards_plaza.php">Orchards Plaza</option>
                <option value="projects/parkland_terrace.php">Parkland Terrace</option>
                <option value="projects/parkside_village.php">Parkside Village</option>
                <option value="projects/pisqah_harriet.php">Pisqah/Harriet</option>
                <option value="projects/plaza_los_robles.php">Plaza Los Robles</option>
                <option value="projects/rivermark_hawthorne.php">Rivermark Hawthorne</option>
                <option value="projects/riverplace.php">Riverplace</option>
                <option value="projects/salem_24hr_fitness.php">Salem 24hr Fitness</option>
                <option value="projects/sandhill.php">Sandhill</option>
                <option value="projects/shoreview_dental.php">Shoreview Dental</option>
                <option value="projects/solhaven.php">Solhaven</option>
                <option value="projects/stewart_terrace.php">Stewart Terrace</option>
                <option value="projects/st_joesph.php">St. Joseph Shelter</option>
                <option value="projects/stonebrook.php">Stonebrook</option>
                <option value="projects/sunrise.php">Sunrise</option>
                <option value="projects/summit_park.php">Summit Park</option>
                <option value="projects/the_village.php">The Village at Monmouth</option>
                <option value="projects/tillamook_ymca.php">Tillamook YMCA</option>
                <option value="projects/tillicum_court.php">Tillicum</option>
                <option value="projects/tri_harbor.php">Tri-Harbor</option>
                <option value="projects/tryon_mews.php">Tryon Mews</option>
                <option value="projects/uptown.php">Uptown Tower</option>
                <option value="projects/vermont_springs.php">Vermont Springs</option>
                <option value="projects/villebois_dental.php">Villebois Dental</option>
                <option value="projects/villa_de_suenos.php">Villa de Suenos</option>
                <option value="projects/villa_West.php">Villa West</option>
                <option value="projects/vittoria.php">Vittoria</option>
                <option value="projects/walnutPark.php">Walnut Park</option>
                <option value="projects/watercrest.php">Watercrest</option>
                <option value="projects/west_alameda.php">West Alameda</option>
                <option value="projects/westgate_terrace.php">Westgate Terrace</option>
	   </select></div></div>
